# .github/workflows/android-build.yml
name: Android CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-apk:
    runs-on: ubuntu-24.04

    steps:
      # 1. Check out your code
      - uses: actions/checkout@v3

      # 2. Install a JDK (Buildozer needs Java for Android tooling)
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '11'

      # 3. Install Android SDK command-line tools, platform-tools, build-tools & a platform
      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
        with:
          # installs sdkmanager, aapt, aidl, etc.
          packages: |
            platform-tools
            build-tools;33.0.2
            platforms;android-33
          accept-android-sdk-licenses: true   # auto-accept licenses :contentReference[oaicite:0]{index=0}

      # 4. Install Python and Buildozer (plus Cython so it’s detected)
      - name: Set up Python & Buildozer
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - run: |
          python -m pip install --upgrade pip buildozer Cython

      # 5. Build the debug APK
      - name: Build Debug APK
        run: |
          # Uncomment if this is your first run and you don’t have buildozer.spec yet:
          # buildozer init
          buildozer -v android debug

      # 6. Upload the APK for download
      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: myapp-debug-apk
          path: bin/*.apk
