# .github/workflows/android-build.yml
name: Android CI

on:
  push:      { branches: [ main ] }
  pull_request: { branches: [ main ] }

jobs:
  build-apk:
    runs-on: ubuntu-24.04

    steps:
      # 1. Checkout
      - uses: actions/checkout@v3

      # 2. JDK 17 for sdkmanager
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '17'

      # 3. Install Android SDK + build-tools, platform-tools, platforms
      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
        with:
          packages: >
            platform-tools
            build-tools;33.0.2
            platforms;android-33
          accept-android-sdk-licenses: true

      # 4. Python & Buildozer (+ Cython)
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - run: |
          python -m pip install --upgrade pip
          python -m pip install buildozer Cython

      # 5. Build APK
      - name: Build Debug APK
        run: |
          # buildozer init  # <-- uncomment if first run
          buildozer -v android debug

      # 6. Upload
      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: myapp-debug-apk
          path: bin/*.apk
