# .github/workflows/android-build.yml
name: Android CI

# Trigger on pushes and PRs to main
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-apk:
    name: Build and Upload APK
    runs-on: ubuntu-24.04

    steps:
      # 1. Check out your code
      - uses: actions/checkout@v3

      # 2. Set up Python 3.10
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # 3. Install Buildozer, Cython & Android toolchain deps
      - name: Install Build Dependencies
        run: |
          sudo apt update
          sudo apt install -y \
            build-essential git openjdk-11-jdk unzip zlib1g-dev \
            libffi-dev libssl-dev
          python -m pip install --upgrade pip buildozer Cython

      # 4. Build your APK
      - name: Build Debug APK
        run: |
          # If this is the first time, ensure you have a buildozer.spec:
          # buildozer init
          buildozer -v android debug

      # 5. Upload the resulting APK(s)
      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: myapp-debug-apk
          path: bin/*.apk
