# .github/workflows/android-build.yml
name: Android CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-apk:
    runs-on: ubuntu-24.04

    steps:
      # 1. Check out your code
      - uses: actions/checkout@v3

      # 2. Install JDK 17 (required by the Android cmdline-tools)
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '17'

      # 3. Download & unpack the Android command-line tools
      - name: Install Android SDK command-line tools
        run: |
          export ANDROID_SDK_ROOT=$HOME/Android/Sdk
          mkdir -p $ANDROID_SDK_ROOT/cmdline-tools
          wget -q https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip -O cmdline-tools.zip
          unzip -q cmdline-tools.zip -d $ANDROID_SDK_ROOT/cmdline-tools
          mv $ANDROID_SDK_ROOT/cmdline-tools/cmdline-tools $ANDROID_SDK_ROOT/cmdline-tools/latest
          rm cmdline-tools.zip

      # 4. Use sdkmanager to install platform-tools, build-tools (with aidl), and a platform
      - name: Install Android SDK packages
        run: |
          export ANDROID_SDK_ROOT=$HOME/Android/Sdk
          yes | $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager \
            --sdk_root=$ANDROID_SDK_ROOT \
            "platform-tools" \
            "build-tools;30.0.3" \
            "platforms;android-33"

      # 5. Mirror the new cmdline-tools into the legacy tools/bin path that Buildozer expects
      - name: Create legacy tools/bin layout
        run: |
          export ANDROID_SDK_ROOT=$HOME/Android/Sdk
          mkdir -p $ANDROID_SDK_ROOT/tools/bin
          ln -sf $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/* $ANDROID_SDK_ROOT/tools/bin/

      # 6. Expose your SDK & tools on the runner’s environment
      - name: Configure Android environment
        run: |
          echo "ANDROID_SDK_ROOT=$HOME/Android/Sdk" >> $GITHUB_ENV
          echo "ANDROIDSDK=$HOME/Android/Sdk"       >> $GITHUB_ENV
          echo "ANDROID_HOME=$HOME/Android/Sdk"     >> $GITHUB_ENV
          echo "$HOME/Android/Sdk/platform-tools"   >> $GITHUB_PATH
          echo "$HOME/Android/Sdk/build-tools/30.0.3" >> $GITHUB_PATH
          echo "$HOME/Android/Sdk/tools/bin"        >> $GITHUB_PATH

      # 7. Replace any existing Buildozer SDK stub with your real SDK
      - name: Link Android SDK for Buildozer
        run: |
          rm -rf ~/.buildozer/android/platform/android-sdk
          mkdir -p ~/.buildozer/android/platform
          ln -s $HOME/Android/Sdk ~/.buildozer/android/platform/android-sdk

      # 8. Set up Python & install Buildozer + Cython
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install Buildozer & Cython
        run: |
          python -m pip install --upgrade pip
          python -m pip install buildozer Cython

      # 9. Build your debug APK
      - name: Build Debug APK
        run: |
          # Uncomment if you don’t yet have buildozer.spec:
          # buildozer init
          buildozer -v android debug

      # 10. Upload the resulting APK
      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: myapp-debug-apk
          path: bin/*.apk
