# .github/workflows/android-build.yml
name: Android CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-apk:
    runs-on: ubuntu-24.04

    steps:
      # 1. Check out your code
      - uses: actions/checkout@v3

      # 2. JDK 17 for sdkmanager
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '17'

      # 3. Download & unpack Android command-line tools
      - name: Install Android SDK command-line tools
        run: |
          export ANDROID_SDK_ROOT=$HOME/Android/Sdk
          mkdir -p $ANDROID_SDK_ROOT/cmdline-tools
          wget -q https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip \
            -O cmdline-tools.zip
          unzip -q cmdline-tools.zip -d $ANDROID_SDK_ROOT/cmdline-tools
          mv $ANDROID_SDK_ROOT/cmdline-tools/cmdline-tools \
             $ANDROID_SDK_ROOT/cmdline-tools/latest
          rm cmdline-tools.zip

      # 4. Install platform-tools, build-tools (with aidl), & platforms
      - name: Install Android SDK packages
        run: |
          export ANDROID_SDK_ROOT=$HOME/Android/Sdk
          yes | $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager \
            --sdk_root=$ANDROID_SDK_ROOT \
            "platform-tools" \
            "build-tools;30.0.3" \
            "platforms;android-33"

      # 5. Expose SDK & tools on PATH
      - name: Configure Android environment
        run: |
          echo "ANDROID_SDK_ROOT=$HOME/Android/Sdk" >> $GITHUB_ENV
          echo "$HOME/Android/Sdk/platform-tools" >> $GITHUB_PATH
          echo "$HOME/Android/Sdk/build-tools/30.0.3" >> $GITHUB_PATH
          echo "$HOME/Android/Sdk/cmdline-tools/latest/bin" >> $GITHUB_PATH

      # 6. Link your SDK into Buildozer’s default location
      - name: Link Android SDK for Buildozer
        run: |
          mkdir -p ~/.buildozer/android/platform
          ln -sf $HOME/Android/Sdk ~/.buildozer/android/platform/android-sdk

      # 7. Set up Python & install Buildozer + Cython
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install Buildozer & Cython
        run: |
          python -m pip install --upgrade pip
          python -m pip install buildozer Cython

      # 8. Build the debug APK
      - name: Build Debug APK
        run: |
          # buildozer init   # <- uncomment if you don’t have buildozer.spec yet
          buildozer -v android debug

      # 9. Upload the APK artifact
      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: myapp-debug-apk
          path: bin/*.apk
